stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  AWS_DEFAULT_REGION: sa-east-1
  EKS_CLUSTER_NAME: kubernetes-lab

build_images:
  stage: build
  image: docker:29.4.1

  services:
    - docker:29.4.1-dind

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script:
    - docker build -t itallohmp/sgp-notifier:1.0 .
    - docker push itallohmp/sgp-notifier:1.0

deploy_aws:
  stage: deploy
  image: ubuntu:22.04

  before_script:
    - apt-get update
    - apt-get install -y curl unzip

    # instala AWS CLI
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install

    # instala kubectl
    - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/

    # configura acesso ao cluster
    - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $EKS_CLUSTER_NAME

  script:
    - kubectl get nodes
    - kubectl apply -f k8s-deployment.yaml