stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  AWS_DEFAULT_REGION: sa-east-1
  EKS_CLUSTER_NAME: kubernetes-lab

build_images:
  stage: build
  image: docker:29.4.1

  services:
    - docker:29.4.1-dind

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script:
    - docker build -t itallohmp/sgp-notifier:1.0 .
    - docker push itallohmp/sgp-notifier:1.0

deploy_aws:
  stage: deploy
  image: amazon/aws-cli

  before_script:
    - curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.0/2024-01-04/bin/linux/amd64/kubectl
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $EKS_CLUSTER_NAME

  script:
    - kubectl get nodes
    - kubectl apply -f k8s/deployment.yaml