apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgp-notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sgp-notifier
  template:
    metadata:
      labels:
        app: sgp-notifier
    spec:
      containers:
        - name: sgp-notifier
          image: itallohmp/sgp-notifier:1.0
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: sgp-notifier-secret

---
apiVersion: v1
kind: Service
metadata:
  name: sgp-service
spec:
  type: NodePort
  selector:
    app: sgp-notifier
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007